# Generated by Django 5.1 on 2024-08-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='Tutorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.topic'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Tutorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.tutorial'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
