# Generated by Django 5.1 on 2024-08-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_tutorial_user_alter_attachments_tutorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='Tutorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.tutorial'),
        ),
    ]
