# Generated by Django 5.1 on 2024-08-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_attachments_tutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='Tutorial',
            new_name='tutorial',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='Tutorial',
            new_name='tutorial',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
