# Generated by Django 5.1 on 2024-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_tutorial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
