# Generated by Django 5.1 on 2024-08-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_tutorial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(null=True, upload_to='TutorialCoverPhotos'),
        ),
    ]
