# Generated by Django 5.1 on 2024-08-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_user_is_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='are_a_student',
        ),
    ]
