# Generated by Django 5.1 on 2024-08-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_rename_is_student_user_are_a_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='are_a_student',
            new_name='are_you_a_student',
        ),
    ]
