# Generated by Django 5.1 on 2024-08-30 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_rename_are_a_student_user_are_you_a_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.tutorial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
