# Generated by Django 5.1 on 2024-08-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_tutorial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
