# Generated by Django 5.1 on 2024-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_tutorial_image_cat_question_answer_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
