# Generated by Django 5.1 on 2024-09-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_tutorial_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='cat_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='instruction',
        ),
        migrations.AddField(
            model_name='cat',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
