# Generated by Django 5.1 on 2024-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_cat_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
