# Generated by Django 5.1 on 2024-09-06 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_remove_response_is_correct_catsubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
