# Generated by Django 5.1 on 2024-09-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_studentapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
